name: introvertish
description: Introvertish.life frontend UI application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  intl_phone_field: ^3.2.0
  google_fonts: ^6.1.0
  persistent_bottom_nav_bar: ^5.0.2
  url_launcher: ^6.2.4
  dropdown_button2: ^2.3.9
  intl:
  flutter_otp_text_field:
  path_provider: ^2.1.3
  fl_chart: ^0.67.0
  time_chart: ^0.5.5
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  video_player: ^2.9.1
  video_trimmer: ^3.0.1
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato/Lato-Regular.ttf
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans/NunitoSans-Regular.ttf
    - family: FastHand
      fonts:
        - asset: fonts/FastHand/FastHand-Regular.ttf

  assets:
    - assets/ScreenImages/
    - assets/posts/
    - assets/Json/sample.json
    - assets/images/
